version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: node_csv
    container_name: csv
    volumes:
      - ./src:/app/src
    ports:
      - '${PORT}:${PORT}'
